user = "guest"
filename = "test"
number_test = 5
substitute_test = "map"
list = [
    "first",
    "second",
    "third"
]
gospecific = ["Go", "lang"]

[map]
test = "testmap"
nottest = "not a test map"
